-- View Dash Board at link https://app.snowflake.com/ap-southeast-1/jh59432/#/visualize-d4vdsmkn8
USE WAREHOUSE SMALLWAREHOUSE;
USE DATABASE TESTDB;
USE SCHEMA ECOMMERCE;
SHOW TABLES;

-- INVOICES TABLE
SELECT COUNT(DISTINCT COUNTRY) AS NUMBER_COUNTRIES FROM INVOICES;
-- TOP 2-10 countries with most clients
SELECT COUNTRY, 
       COUNT(DISTINCT CUSTOMERID) AS N_CLIENTS   
FROM INVOICES
-- REMOVE UK AS IT HAS TOO MANY CLIENTS COMPARED TO OTHER COUNTRIES
WHERE UPPER(COUNTRY) NOT LIKE 'UNITED%'
GROUP BY COUNTRY
ORDER BY N_CLIENTS DESC
LIMIT 10;