steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops','.']
# push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']
# deploy the container image to GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=gke.yaml
  - --image='gcr.io/$PROJECT_ID/gcpdevops'
  - --location=us-central1-c
  - --cluster=gke-gcp-devops
  - --namespace=gcp-devops-prod

